[build]
builder = "nixpacks"

[deploy]
restartPolicyMaxRetries = 5

[[services]]
name = "backend"
processingType = "web"
startCommand = "node src/server.js"

[[services.directories]]
source = "backend"
destination = "/app"
